name: CI

on:
  push:
    branches: [ master, rc, "feat/**", "fix/**" ]
  pull_request:
    branches: [ master, rc ]

jobs:
  build-test:
    uses: ./.github/workflows/ci-jobs/build-test.yml

  sonar:
    needs: build-test
    uses: ./.github/workflows/ci-jobs/sonar.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
