name: CI

on:
  push:
    branches: [ "feat/**", "fix/**" ]

  pull_request:
    branches: [ master ]

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml

  sonar:
    if: github.event_name == 'pull_request'
    needs: build-test
    uses: ./.github/workflows/sonar.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
