name: CI

on:
  push:
    branches: [ master, rc, "feat/**", "fix/**" ]
    paths-ignore:
    - '.github/**'
    
  pull_request:
    branches: [ master, rc ]
    paths-ignore:
    - '.github/**'

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml

  sonar:
    needs: build-test
    uses: ./.github/workflows/sonar.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
