name: release -> rc merge-back

on:
  push:
    branches: [release]
    paths-ignore:
      - '.github/**'

jobs:
  merge-back:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Auto merge release -> rc
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: rc
          branch: release
          title: "chore(sync): release -> rc"
          body: "Automatyczny merge-back po merge do release"
          
      - name: Enable auto-merge
        run: |
          gh pr merge \
            --auto \
            --merge \
            --repo "${{ github.repository }}" \
            --base rc \
            --head release || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          